name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Release Please will automatically detect package.json and handle versioning
          release-type: node
          # Optional: customize the package name
          package-name: cypress-mochawesome-reporter-v2

